### ISSUE TITLE
Support for Twilio Client Web Javascript Library

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#11]
Add Support for https://www.twilio.com/docs/client/twilio-js. Currently we provide WebRTComm as a WebRTC library but to simplify application portability, the support of the Twilio Client API is needed and can be layered on top of WebRTComm

**Comment by atsakiridis** [comment]
@deruelle I didn't know an issue already existed so I went ahead and opened a similar issue in webrtcomm a couple of days back. Let me close that other one and keep this one for tracking. I assume this new layer on top of webrtcomm will be a new GitHub repo, right?

**Comment by deruelle** [comment]
Actually that's fine I guess we can keep it there and close this one here. And keep the code in the webrtcomm repo

**Comment by atsakiridis** [comment]
Cool @deruelle, let me update
