### ISSUE TITLE
Registering number warning dialog warns user for "undefined" cost

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#118]
By default, Restcomm assumes that charging is not done by DID and by the minute. Unless configured otherwise, the dialog that pops up during number registration, should not warn the user that there is "undefined" cost associated with the registration. Instead the warning should not appear, unless an actual cost is passed through to the end user. 

When the cost is undefined, the warning dialog should not appear until the user approaches their limit of DIDs per Restcomm instance. In which case the dialog should read:

"Are you sure you want to register number ....? This is the last number you can register with your current account. Your account is currently limited to .... numbers. To request additional numbers, please contact your Restcomm support representative or support@telestax.com."

![screen shot 2014-11-16 at 12 12 27 pm](https://cloud.githubusercontent.com/assets/2234901/5063232/6e4c5f9e-6da3-11e4-95ea-a6fbea982afd.png)

**Comment by brainslog** [comment]
PR https://github.com/Mobicents/RestComm/pull/249
