### ISSUE TITLE
Allow configuration to limit the max number of PSTN numbers registered in a Restcomm instance

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#121]
Currently there is not limit of PSTN DIDs that can be allocated to a Restcomm instance. Introducing a configuration parameter would be useful for sizing a restcomm instance to match the hardware and network capacity its running on. It would be also a way of controlling malicious attempts to register unreasonably high number of DIDs.

**Comment by deruelle** [comment]
Closing this issue as this will be part of #282 to control the number of DIDs that can be assigned to an account. We want this to be controlled per account for RestComm Cloud and not limited to an instance or AMI
