### ISSUE TITLE
Implement max number registration constraint to AMI instances

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#122]
Limit Restcomm instance running on m3.large to maximum of 10 registered DIDs. The user can release and purchase new DIDs, but the total number should not exceed 10.

Ideally we would have an automatic default MAX based on the underlying system resources: CPU, RAM, disk space.

related to issue #121

**Comment by deruelle** [comment]
Closing this issue as we won't support AMI anymore and tying this up into #282
