### ISSUE TITLE
Register new number - Capability Selection broken

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#131]
When registering a number, the UI does not reflect choice of capabilities. For example if the selection is restricted to SMS enabled numbers, the results still show non-SMS enabled numbers.

See screenshots.
![screen shot 2014-12-06 at 5 47 22 pm](https://cloud.githubusercontent.com/assets/2234901/5329376/37b347b8-7d70-11e4-86b3-b7ef84a18c9a.png)
![screen shot 2014-12-06 at 5 47 26 pm](https://cloud.githubusercontent.com/assets/2234901/5329377/3bc96b52-7d70-11e4-9339-fa0acd72a40f.png)
![screen shot 2014-12-06 at 5 50 34 pm](https://cloud.githubusercontent.com/assets/2234901/5329381/6b3f00e0-7d70-11e4-8990-3eba215c88d6.png)
![screen shot 2014-12-06 at 5 50 25 pm](https://cloud.githubusercontent.com/assets/2234901/5329382/6d710052-7d70-11e4-9dc6-64565766a6ca.png)

**Comment by brainslog** [comment]
PR #252 sent
