### ISSUE TITLE
Add provisioningUrl packaging option and notify it on respective events

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#158]
Introduce new configurationUrl option when packaging. Vendor should be able to define a url that will be sent the configuration parameters when these are saved.
Both RVD and adminUI need to be modified.

**Comment by deruelle** [comment]
Shall we have only one callback URL only called provisioningURL for the sake of simplicty on the app developer side and to avoid profileration of callback URLs 
ProvisioningURL would have a parameter describing what type of call back it is ie DID Provisioning, App Parameters Provisioning, App Install Provisioning, User Provisioning, ... ? 
If the app is updated to the latest version could also be useful.

**Comment by ivelin** [comment]
That's fine with me.

**Comment by otsakir** [comment]
deruelle, I agree. It will be much easier to maintain the specification of a single callback service than to add new parameters to the packaging specification whenever new requirements come up.

We could add additional callback URL in the future if they are really needed.
