### ISSUE TITLE
Add versioning to RAS applications

### ISSUE THREAD

**Issue by otsakir** [Mobicents/RestComm#180]
Currently, a RAS application supports versioning for the enclosing RVD project as well as the iteration of application submitted by the vendor (ABCauto 1, 2..). 

However there is no versioning for the package itself or the specification of the scripts that may accompany the application. For example, provisioning scripts have a specific REST interface. All this, although it currently exists, it should be defined in a specification draft and be assigned a version number. 

RestcommUI reject incompatible application versions or issue some kind of warning.

**Comment by ivelin** [comment]
I think this relates to the version of the platform that the app is certified on. For example the app metadata should state that the app was tested and certified on Restcomm versions between 7.3.0 and 7.3.4.

The Restcomm platform should respectively ensure some standard versioning conventions. Backwards API compatibility is guaranteed for minor (7.x) and point (7.x.y) versions. Minor versions (7.4) can introduce new features, but not break API compatibility. Major new versions can break compatibility (8).

**Comment by otsakir** [comment]
Ok, got it. 

The RAS application version can relate to Restcomm version indirectly too. It allows for more flexibility. We can use a simpler versioning scheme for RAS application like 1, 2, 3 etc. There will be some sort of mapping between RAS application versions and Restcomm version. The same has been done for RVD projects which do not follow Restcomm versioning although they (should) respect it. 

For example, suppose simple integer versioning is used for RAS application HTTP api. Current version would be 5. When we move from Restcomm 7.x to Restcomm 8, IF, there are any changes in the API (most probably will be), a new RAS application HTTP api version would be created, namely, 6. Otherwise, we stick to 5.

**Comment by ivelin** [comment]
That's a nice compatibility enforcement idea via versioning schemas co-relation.
