### ISSUE TITLE
Need to expose 'text' property of SMS message as core variable

### ISSUE THREAD

**Issue by scottbarstow** [Mobicents/RestComm#194]
Right now the only variables available for an SMS are core_From, core_To, SmsSid, and SmsStatus.  There is not a way (that I can find) to get the text / contents of the message in an App. 

Submitting for consideration, but also willing to make the mods myself if I can get some general direction.  The only place I can find where these variables are mentioned is in services.js in restcomm.rvd project.

**Comment by ivelin** [comment]
Good point, @scottbarstow . This issue has been brought up before. I think there may be an open ticket for it. 

@gvagenas , @otsakir is this still work in progress, or the variable is available in the latest upstream code?

**Comment by scottbarstow** [comment]
Ok.  I need to be in the habit of searching issues ahead of filing.  Thanks
for that reminder

On Mon, Mar 16, 2015 at 6:15 PM, ivelin <notifications@github.com> wrote:

> Good point, @scottbarstow <https://github.com/scottbarstow> . This issue
> has been brought up before. I think there may be an open ticket for it.
>
> @gvagenas <https://github.com/gvagenas> , @otsakir
> <https://github.com/otsakir> is this still work in progress, or the
> variable is available in the latest upstream code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mobicents/RestComm/issues/194#issuecomment-81964271>.
>



-- 
scottbarstow.com
@scottbarstow

**Comment by otsakir** [comment]
Thanks for reporting this @scottbarstow .

Using the $core_Body variable to access SMS body should already work. This variable however is not in the variable dropdown (had been forgotten). This has been fixed by #174 but not yet merged in the master mobicents branch.

**Comment by scottbarstow** [comment]
Indeed it does.  Thanks!

On Tue, Mar 17, 2015 at 2:42 AM, Orestis Tsakiridis <
notifications@github.com> wrote:

> Thanks for reporting this @scottbarstow <https://github.com/scottbarstow>
> .
>
> Using the $core_Body variable to access SMS body should already work. This
> variable however is not in the variable dropdown (had been forgotten). This
> has been fixed by #174 <https://github.com/Mobicents/RestComm/issues/174>
> but not yet merged in the master mobicents branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mobicents/RestComm/issues/194#issuecomment-82154102>.
>



-- 
scottbarstow.com
@scottbarstow

**Comment by scottbarstow** [comment]
Closing this out tomorrow unless anyone objects.  This is working as advertised for me.
