### ISSUE TITLE
Remember RVD language accross when page refresh

### ISSUE THREAD

**Issue by otsakir** [Mobicents/RestComm#199]
The language setting of the translation extension gets lost when refreshing the page, starting RVD on a new tab etc. Some sort of storage (preferably cookie based) could be used to persist such kind of information. 

This may help:

https://github.com/angular-translate/angular-translate/wiki/Multi-Language#let-your-app-remember-the-language

**Comment by ghjansen** [comment]
@otsakir sorry about my late, busy week.
The page refresh behavior seems to be unstable. Sometimes the selected language still the same, but sometimes not. I searched for known issues about that but didnt find nothing relevant.
Could you check my commit and let me know what you think?

**Comment by otsakir** [comment]
No problem @ghjansen . I will look into the issue and post my findings.

**Comment by ghjansen** [comment]
Seems to be stable now @otsakir . It was just the way we set the default language. By doing the proper way, the browser don't loose the cookies anymore (both page refresh and multiple tabs). There is only a extreme case involving safari, where fast refreshing multiple times the page makes the browser loose the cookie and apply the default language. I have more information here if you confirm to go ahead in this way.

**Comment by otsakir** [comment]
Sounds good @ghjansen. Go ahaid with the implementation.The safari case sounds extreme to worry about.
