### ISSUE TITLE
Enable native lightweight SMPP support in Restcomm

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#207]
In many cases Restcomm has to connect to an SMSC over SMPP. Often it is overkill to introduce a full blown SMSC that can translate from SIP to SMPP traffic.

It would reduce Restcomm deployment friction if basic SMPP connectivity is directly supported, without store and forward, retry and other complex delivery modes that are typically handled by an SMSC.

**Comment by gvagenas** [comment]
@croufay can we close this issue?

**Comment by deruelle** [comment]
Duplicate of https://github.com/Mobicents/RestComm/issues/365

**Comment by ivelin** [comment]
Yay!!
