### ISSUE TITLE
RVD hiding tabs feature is not user friendly

### ISSUE THREAD

**Issue by hrosa** [Mobicents/RestComm#213]
All users experimenting the latest version of RVD which includes the "hide module" feature were confused. Once the project is closed and reopened they all wondered where their modules were.

RVD should remember which modules were open at the time the project was last closed and show them when the project is reopened.
Also, we should inform better the users how they can access the hidden module list. The current dropdown button is not noticeable.

**Comment by otsakir** [comment]
Helpfull hints can also be displayed when new features are installed. See #214 .

**Comment by deruelle** [comment]
Orestis, can we have something similar to Eclipse, where you have a number
of Modules (Tabs) open like 5 or 6 max and then at the end (right hand
side) have a double arrow going down on when you click on it list the rest
of the hidden tabs, and if you click on it it replaces one of the open ones
? I think it would improve the usability.

Jean

**Comment by ghjansen** [comment]
Hi! Talking about improvements in editor: I've been thinking if maybe the steps menu located left could follow the page scroll. I missed this feature in my last experience building a app, it becomes non ergonomic as the app's growth.

What you think?

**Comment by deruelle** [comment]
+1. That's a good idea. Wanna try to contribute it ?

Jean

**Comment by otsakir** [comment]
I totally agree. Dragging elements down across the page can be a pain as
the module size grows.

I've created an issue for this:

https://github.com/Mobicents/RestComm/issues/232

**Comment by ghjansen** [comment]
Yes, let's do it! I will assign #232 to myself and work on it this weekend.

**Comment by otsakir** [comment]
That's great ghjansen! Refer me if you need any help...

**Comment by otsakir** [comment]
I created a new issue for 'remembering open modules' https://github.com/Mobicents/RestComm/issues/403
The other aspect of this issue regarding easily accessing hidden modules has been fixed.
