### ISSUE TITLE
IncomingPhoneNumbers Endpoint, problem to register real number (tries to get it from ProvisionProvider)

### ISSUE THREAD

**Issue by gvagenas** [Mobicents/RestComm#219]
IncomingPhoneNumbers Endpoint, problem to register real number (tries to get it from ProvisionProvider)

**Comment by deruelle** [comment]
George, this is now available and fixed in the issue-169 branch, I'll do a pull request in the next couple days.

**Comment by gvagenas** [comment]
Jean, the patch is ready from the TS branch and I just cherry picked the commits here, no need for PR

**Comment by deruelle** [comment]
Currently if you try to register a SIP number that looks like a real number
it will fail
the patch that's part of the voxbone integration is better in the issue-169
branch as we do a real difference on whether the user is registering a SIP
number or not and if the provisioning manager is not null.

Jean

**Comment by gvagenas** [comment]
ok great, please do a PR and I will check the patch and merge it to the master

**Comment by deruelle** [comment]
Yeah I just needed to improve the unit tests and test the Voxbone SIP
Integration with Sacha and I'll do the PR.

Jean
