### ISSUE TITLE
Can't embed a url in any application setup fields

### ISSUE THREAD

**Issue by scottbarstow** [Mobicents/RestComm#229]
I tried to add a link to the "How To" section of the App Configuration so that I could send the user to a detailed configuration page for the app.  I tried just putting an HTTP link and putting an anchor tag. Neither worked.

I then tried just putting a url in the Web UI link, and that is not working for me either.  When I click the button, nothing happens.  No errors in the JS console, just... nothing. 

On the 2nd issue, I added the Web UI link after initial configuration.  I am testing all in local environment, no distribution or zipping at this time.

**Comment by otsakir** [comment]
Scott, on the first issue, there is no markup allowed in the text fields. That's an angular restriction for security reasons. I'll see what we can to do to loosen this.

On the second issue please confirm:

1. From RVD you have gone through packaging your application and provided a link in the "Web UI" field. 
2. You saved the packaging information
3. In AdminUI you are viewing the configuration page of the application
4. You press the WebUI button and nothing happens
5. You have cleared all your browser caches (in case you have launched previous versions of RVD/AdminUI from the same host/port)

The WebUI should work no matter if it was defined on initial configuration or configured later.

What was the uri you specified in WebUI btw?

**Comment by scottbarstow** [comment]
Did all that, did not clear cache 
Url is:  http://scottbarstow.com/restcomm-text-to-slack-application-configuration/
