### ISSUE TITLE
Add 'log RCML' option

### ISSUE THREAD

**Issue by otsakir** [Mobicents/RestComm#235]
**UI**
Refine RVD's application logging settings. Add an option that will toggle logging the RCML output as a sub-option of 'Enable application logging'. 

**Server side**
When the respective setting is enabled, hook RvdController and log the RCML response to the application log.

**Comment by otsakir** [comment]
Hello @ghjansen , interested in taking a bite? 

Having the RCML in the application log would greatly reduce administrative overhead and help dig into RCML issues.

**Comment by ghjansen** [comment]
For sure @otsakir ! Can I keep branching from rvd_master per issue?

**Comment by otsakir** [comment]
Hello @ghjansen 

Yes, branching from rvd_master will be fine for now.

**Comment by ghjansen** [comment]
@otsakir the log messages are stored through a JSON marshaler, replacing special characters by its respective unicodes. Assuming this, i've tryed to handle the unicode sequences on client-side, before fill the log's textarea by using ngSanitize($sanitize), Strict Context Escaping($sce), eval, ... but none of them worked as expected. So I used regexp to slightly recover the RCML tags appearance by replace some characters. Do you know a better way to do this? The encoded characters are present in different parts of log file, not only in RCML messages. (Commit 04a37464a8a9cd53207f1637b3b27fc9275114a3)

**Comment by otsakir** [comment]
Great initiatives @ghjansen. I think however the problem lies with the server and not the client. But first some background on application logging internals:

The application log file is a mixture of a simple line based text file that occasionally can contain JSON formatted data. The reason we don't use only plain JSON is that there is no easy way to append some content and persist unless  you reload and parse the whole file. So, just adding a new log entry to a 1000 entry file would require reloading and parsing all previous 1000 json entries. It is also easier to manually review a text file using a common text editor, grep some tags or sort it.

On the other hand, line based text files are not very descriptive about their content and especially when using External Services there can be some pretty complex responses and we need the JSON syntax to display them. 

The ProjectLogger uses a very generic log() method and passes everything through a JSON encoder. And here i believe is our (my) error. 

My suggestion is to do some kind of overloading or type checking there so that for RCML (String) payload there is no conversion to JSON and is returned as is. At the same time at the client ngSanitize should work right.

Still, for log entries where actual objects will result in the cryptic /uXXXX sequeces. But at least we will have the RCML output right.

Comments?

**Comment by ghjansen** [comment]
Thank you @otsakir for your explanation! I imagined that was about something like that on server side, but without much sure. I think a log() overload, as you suggested, will be good. A additional boolean at this point will be enough to skip marshaler when done(). Also it came to my mind apply varargs with a logging options enum, considering future new options for logging, but seems not fits so well. I'll proceed on overloading and keep updates here, thank you!

**Comment by ghjansen** [comment]
I think now it's ok. Even the XML indentation is kept. Please let me know if there is something else.
![screen shot 2015-08-19 at 10 37 19](https://cloud.githubusercontent.com/assets/1459428/9357777/29bc93e0-465f-11e5-839e-c95cfd50a2a9.png)
