### ISSUE TITLE
Restcomm SMPP Connector for SMSCGateway (v5.X/v3.X)

### ISSUE THREAD

**Issue by jfcvm** [Mobicents/RestComm#260]
Currently, only SIP connector exists for Restcomm/SMSC connectivity. SMPP is more ideal for a telecomm infrastructure. Target SMPP versions using Cloudhopper SMPP are v5.x and v3.x.

**Comment by abhayani** [comment]
Yes we are in process of adding SMPP capability in RestComm.

**Comment by jfcvm** [comment]
In my haste, this appears to be a duplicate issue. Please refer to https://github.com/Mobicents/RestComm/issues/207.
