### ISSUE TITLE
Admin-UI Search DID is not working

### ISSUE THREAD

**Issue by gvagenas** [Mobicents/RestComm#265]
Admin-UI Search DID is not working

Checking with Chrome Developer tools the HTTP Get request to Restcomm AvailablePhoneNumbersEndpoint is missing the areaCode path parameter.

**Comment by brainslog** [comment]
Pull Request #266

**Comment by gvagenas** [comment]
Pull request merged.

Thanks Alex

On Sun, May 24, 2015 at 4:20 AM, brainslog <notifications@github.com> wrote:

> Pull Request #266 <https://github.com/Mobicents/RestComm/pull/266>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mobicents/RestComm/issues/265#issuecomment-104962420>.
>



-- 
George Vagenas
