### ISSUE TITLE
First time user registration - Collect E-Mail from user on instance activation

### ISSUE THREAD

**Issue by desipepova** [Mobicents/RestComm#28]
We need a way to identify users for survey, newsletter, password reset, automatic updates and support.

**Comment by ivelin** [comment]
Great video walk through of this feature by Lefteris @leftyb !

@otsakir,  would it be possible to incorporate this feature into SSO for the upcoming 7.3.1 , release?

https://www.youtube.com/watch?v=6UW2QJPfTRc&feature=youtu.be

**Comment by leftyb** [comment]
Hi,

Maybe with some modifications can be useful feature for registering a new
user Restcomm copy.
We are in the process of revising it with Orestis.

Thank you,
Lefteris

**Comment by otsakir** [comment]
@ivelin , by all means. Instance registration seems like a very nice fit in the SSO workflow. Registering an instance could mean entering the SSO authentication mechanism, creating a security realm for the instance etc.
