### ISSUE TITLE
Map / to /restcomm

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#281]
When installing restcomm via Kitematic , the default web preview assumes / for the restcomm image home page. That results in a blank page response. Let's map / to /restcomm so the kitematic user experience is smooth. See related article and screenshots.

http://docs.docker.com/kitematic/userguide/
"The summary page will show different things depending on the image metadata. If a known "web" port (see below) is EXPOSED, then Kitematic assumes its a web page, and will show a preview of the site at /. If other ports are exposed, then it will show a list of those ports, and the Docker daemon IP and port they are mapped to. If there are any VOLUMES, then these will be shown. At minimum, the summary screen will show the main container process' log output.

The currently detected "web" ports are, 80, 8000, 8080, 3000, 5000, 2368, 9200, and 8983.
"

![screen shot 2015-06-02 at 10 15 34 am](https://cloud.githubusercontent.com/assets/2234901/7939856/cba972f2-0912-11e5-95ab-b4e5b62d7d24.png)

**Comment by gvagenas** [comment]
Documentation, tutorials and quick user guides should now change to make clear that Restcomm Management UI is now accessible at the root context (/).

**Comment by ivelin** [comment]
The updated image works great. See screenshot.

![screen shot 2015-06-02 at 11 14 38 pm](https://cloud.githubusercontent.com/assets/2234901/7952575/367754fe-097d-11e5-9961-39b19188ef78.png)

**Comment by otsakir** [comment]
Is the /restcomm/ path still enabled?

We could provide some sort of redirect from / to /restcomm and have both paths functional so that backwards compatibility is kept.

**Comment by desipepova** [comment]
Documentation on docs.telestax.com was successfully updated,
