### ISSUE TITLE
Monitoring Service

### ISSUE THREAD

**Issue by gvagenas** [Mobicents/RestComm#283]
To provide live traffic statistics and alive pings

**Comment by ivelin** [comment]
related to https://github.com/Mobicents/sip-servlets/issues/60
and
https://github.com/Mobicents/smscgateway/issues/1

**Comment by gvagenas** [comment]
The monitoring service is planned for the next development iteration.
It will collect statistics and will serve them on-demand. Also I am planning to provide a hook where listeners can register and receive specific events from the service.

**Comment by ivelin** [comment]
OK. Do we need to create a separate issue for a listener that communicates with a cloud service to gather stats from around the world?

**Comment by gvagenas** [comment]
I don't think so, this listener will have to implement the same interface like all the listeners.
