### ISSUE TITLE
Automatically release DIDs when AMI is terminated

### ISSUE THREAD

**Issue by desipepova** [Mobicents/RestComm#31]
In the upcoming AMI we will integrate VI by default to simplify the end user experience. 
If a customer registers DIDs and consequently kills the AMI, we need to make sure to release the DIDs from the VI portal.

**Comment by ivelin** [comment]
When the user stops an AMI we should give it a week or two before releasing DIDs. But if the user Terminates an AMI, we should release DIDs immediately.

**Comment by ivelin** [comment]
We discussed this issue during Mobicents IRC chat on Jan 7 and decided to only implement DID clean up on Terminate for now. AMI Stop is a case we need to study further.

gvag: There are two things need to be done,
[10:50am] gvag: first Pavel will take care to send the Service Proxy the event that EC2 instance is terminated
[10:50am] Desi: Voicemail to Email has to be uploaded soon.
[10:50am] gvag: and second the script at the Service Proxy that will cleanup the DIDs
