### ISSUE TITLE
Add Routing Decision to RVD based on SMS text content

### ISSUE THREAD

**Issue by croufay** [Mobicents/RestComm#315]
Adding a search feature that allows users to make routing decision based on content of SMS will reduce the use of External Service and make creating SMS apps much easier.

**Comment by otsakir** [comment]
I'd propose a more generic control element based on variable content. It would work for SMS but other cases too. 

It would take an RVD expression on one side and a number of mappings on the other. The mappings would consist of values and modules. The same as ES mapped routing.

wdyt?

**Comment by desipepova** [comment]
It sounds great Orestis. No need of extra code anymore while developing SMS
applications.

On Thu, Jun 25, 2015 at 11:29 AM, Orestis Tsakiridis <
notifications@github.com> wrote:

> I'd propose a more generic control element based on variable content. It
> would work for SMS but other cases too.
>
> It would take an RVD expression on one side and a number of mappings on
> the other. The mappings would consist of values and modules. The same as ES
> mapped routing.
>
> wdyt?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mobicents/RestComm/issues/315#issuecomment-115161564>.
>



-- 
Desislava Pepova
Customer Care Specialist - Telestax, Inc.

**Comment by croufay** [comment]
That will be great, it should help with making sms apps easier

**Comment by otsakir** [comment]
Right. I've started a new issue for this and marking current as duplicate.

https://github.com/Mobicents/RestComm/issues/317
