### ISSUE TITLE
Restcomm generate instance ID

### ISSUE THREAD

**Issue by gvagenas** [Mobicents/RestComm#369]
Generate instance ID and store it to DB

**Comment by otsakir** [comment]
@gvagenas , can you elaborate a little on that? Give a sample of this identifier where it will be used, if it will be kept secret etc? There is already some sort of discussion on the SSO thread and may come in handy.

**Comment by gvagenas** [comment]
@otsakir , I was thinking to reuse the Amazon EC2 instance id if available (when running at AWS) or create a new unique id the first time that Restcomm starts.

I created the issue about the Restcomm instance id for the needs of monitoring. For example have one monitoring server that collects data from many Restcomm instances.
I wasn't thinking to keep the instance id secret as it would be used for reporting purposes only.

What do you have in mind for instance id?
