### ISSUE TITLE
Outgoing Call CDR duration should start from the time of the Queue

### ISSUE THREAD

**Issue by gvagenas** [Mobicents/RestComm#370]

**Comment by ivelin** [comment]
@gvagenas ,  there is a new forum question related to this change. Can you please comment.

https://groups.google.com/forum/#!topic/restcomm/767tPTCXxxA

**Comment by deruelle** [comment]
In addition to the Billing concern which is the most important one, the Twilio compatibility concern is also strong where we ought to have the same behavior. We can introduce a new attribute that gives the total time including ringing if needed

**Comment by leftyb** [comment]
Hi, 
I gave a look at this issue and I can try to make the appropriate modifications in conjunction with @gvagenas  suggestions.

**Comment by ivelin** [comment]
Thank you, @leftyb

**Comment by gvagenas** [comment]
Great @leftyb . Ping me if you need anything here.

**Comment by leftyb** [comment]
Hi I did a modification, that the duration of the outbound call in CDR include only the "talk time", because before both "ringing time + talk time" were included at the duration time. Is it necessary as well to add a new  element that gives the ringing duration, as was discussed at the forum? e.g "Call.ringDuration".

**Comment by ivelin** [comment]
@leftyb Sounds good, but where is the corresponding code commit?

**Comment by leftyb** [comment]
Hi, @ivelin  I just saw your comment. I am working on this subject, yes i think that we can close this issue by this week. I will do the commit by Wednesday.  I had the modification done, only for the duration time, but not for the new element about the ringing time, now I am working on it. I thought that is better to commit everything at the same time. Although still need to test the duration time to an AMI for DID outbound calls.  If you prefer to commit first the duration time and then the new ringing time element, I can do the tests on the AMI and then commit.

**Comment by ivelin** [comment]
@leftyb  Thank you for the update.

Release early, release often :)
https://en.wikipedia.org/wiki/Release_early,_release_often

Let's push the call duration change so @peteroyle can test it. Then continue with the ring time attribute.
https://groups.google.com/forum/#!topic/restcomm/767tPTCXxxA

**Comment by leftyb** [comment]
Sure @ivelin,  I will do some tests with an AMI, and will commit today the first part. :)

**Comment by leftyb** [comment]
Modifications for review. Tomorrow I will do the pull request after some few more tests.

**Comment by ivelin** [comment]
Great @leftyb .

@peteroyle would you like to review this commit?

**Comment by peteroyle** [comment]
Sure @ivelin what sorts of comments would you be looking for at this stage? Just that it does what I'm expecting or code formatting etc as well?

**Comment by ivelin** [comment]
@peteroyle mainly functionality. Does it do what you expect? Are there omissions? Edge cases. Documentation gaps? 

If you have any concerns, would be best if you could offer Arquillian unit tests that expose the issues and can be used going forward in CI/CD on Jenkins/CloudBees.

**Comment by peteroyle** [comment]
@ivelin, I can't see anything wrong with the code, but unfortunately without understanding how all the RestComm code hangs together I can't tell whether or not it does what it's supposed to. Once @leftyb adds the tests I'll probably have a better chance of understanding those.

**Comment by leftyb** [comment]
Hi @peteroyle,

Thank you for your update. I am working on the tests, as soon as they are ready, I will contact you to check the functionality. In the meanwhile probably you can try, if you like, to copy the compiled .jars (interpreter, telephony) at the ~Restcomm/standalone/deployments/restcomm.war/WEB-INF/lib/ and restart Restcomm.

**Comment by leftyb** [comment]
Hi @peteroyle,

I added two functions to test the modification on the issue. 
1.)testDialCallDurationAliceAnswers(). Running this test you can test both CDR->"duration" & "DialCallDuration".
2:)testDialCallDurationAliceBusy(). This can be used to make sure that, when a call is busy, the duration is zero and it not includes the ringing time (as it was happening before).

You can run them with the following commands from a terminal:
mvn test -pl :restcomm.testsuite  -Dtest=DialActionTest#testDialCallDurationAliceAnswers

mvn test -pl :restcomm.testsuite  -Dtest=DialActionTest#testDialCallDurationAliceBusy

Please tell me if you have any suggestion or need any clarification.

Regards.

**Comment by leftyb** [comment]
The modifications will be committed at the issue #445.

**Comment by peteroyle** [comment]
Hi @leftyb, thanks for the update. I haven't had time to do any actual testing yet with the binaries but I've just had a look at your test code and it looks to me like it confirms the behaviour I'm expecting.

**Comment by peteroyle** [comment]
Hi everyone. I've noticed #445 doesn't have any milestone attached and unless I'm reading it wrong the corresponding pull request was closed but not merged. Just wanted to know if #445 is on the roadmap and if so which version it's targeting?

**Comment by peteroyle** [comment]
Yep, I was reading it wrong, just found the updated pull request (526).
