### ISSUE TITLE
Restcomm doesn't respect the transport used in REGISTER with iOS Messenger

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/RestComm#379]
Scenario:

- register alice from ios messenger (Sofia is setup to always use TCP transport as discussed in another github issue)
- use jitsi to call application 1238 
- Restcomm calls alice
- the incoming call from Restcomm to messenger is using UDP instead of TCP

I would expect it to use TCP since messenger has registered using TCP and has generally used TCP all along

**Comment by gvagenas** [comment]
Patch for this is ready but testsuite fails because of SipUnit issue: https://github.com/Mobicents/sipunit/issues/4

**Comment by gvagenas** [comment]
Because of issue https://github.com/Mobicents/sipunit/issues/4, we cannot have automated tests for that patch. This patch was tested manually by @atsakiridis
