### ISSUE TITLE
Support Chinese for <say> Verb

### ISSUE THREAD

**Issue by leonli-telestax** [Mobicents/RestComm#383]
Ask for support chinese for <say> Verb.

**Comment by leonli-telestax** [comment]
I didn't use virtual designer. I just change the default demo 1235 for hello-world.xml with the following. When I play 1235, it failed after the Enligh annoucement. After I delete chinese, it works well.

<?xml version="1.0" encoding="UTF-8"?>
<Response>
        <Say>Welcome to RestComm, a TeleStax sponsored project.</Say>
        <Say language="zh-cn">欢迎访问在线语音云平</Say>
        <Say language="de">Willkommen bei RestComm einem TeleStax geförderten Projektes.</Say>
        <Say language="fr">Bienvenue à RestComm un projet parrainé par TeleStax .</Say>
</Response>

**Comment by leonli-telestax** [comment]
<?xml version="1.0" encoding="UTF-8"?>
< Response>
        < Say>Welcome to RestComm, a TeleStax sponsored project.< /Say>
        < Say language="zh-cn">欢迎访问在线语音云平< /Say>
        < Say language="de">Willkommen bei RestComm einem TeleStax geförderten Projektes.< /Say>
        < Say language="fr">Bienvenue à RestComm un projet parrainé par TeleStax .< /Say>
< /Response>

**Comment by otsakir** [comment]
It looks like an issue in the TTS restcomm component. Are you using VoiceRSS?

**Comment by leonli-telestax** [comment]
Yes. I am using VoiceRSS which support Chinese perfectly. I can play
chinese by their website demo.

BR

leon

2015-08-19 15:27 GMT+08:00 Orestis Tsakiridis <notifications@github.com>:

> It looks like an issue in the TTS restcomm component. Are you using
> VoiceRSS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mobicents/RestComm/issues/383#issuecomment-132474611>.
>



-- 

李 翔 / Leon Xiang Li

Director of Business Development @ TeleStax

M +86 139 010 79663  / +852 6852 3355  E xli@telestax.com  Web
www.telestax.com

*Communications change the world, Telestax changes the communications*
