### ISSUE TITLE
Make Rescomm Root Admin GUI url backward compatible

### ISSUE THREAD

**Issue by croufay** [Mobicents/RestComm#384]
Make Rescomm Root Admin GUI url backward compatible

At the moment Restcomm instance root URL is 

http://RESTCOMM_IP:8080

If there are redirects to the old url http://RESTCOMM_IP:8080/restcomm-management/ they will fail

Make changes so that both old and new URL work

**Comment by gvagenas** [comment]
Charles,

What redirects to the old URL? Do we have configuration to Restcomm that uses the old Admin UI url?

George

**Comment by croufay** [comment]
I think this issue is no longer applicable and it can be closed
