### ISSUE TITLE
Glitch Noise when Transitioning Audio Files in Play Verb

### ISSUE THREAD

**Issue by croufay** [Mobicents/RestComm#389]
if you create a simple audio app like this

<Response>
<Play>/restcomm/audio/1.wav</Play>
<Play>/restcomm/audio/2.wav</Play>
<Play>/restcomm/audio/3.wav</Play>
</Response>

 the app above will make a glitch sound when transitioning between audio files. 

Confirmed with latest version and also with the following versions: 
7.3.1
mobicents-Restcomm-JBoss-AS7-7.2.1.600

**Comment by deruelle** [comment]
Customer confirmed issue was in his wav files
