### ISSUE TITLE
ACTIVE_PROXY should support 'TRUE'

### ISSUE THREAD

**Issue by peteroyle** [Mobicents/RestComm#391]
In 'release/config-scripts/as7-config-scripts/restcomm/autoconfig.d/config-load-balancer.sh' ACTIVE_PROXY is compared against 'true' but not 'TRUE'. All other scripts compare against both, and the default proxy.conf lists the valid values as 'TRUE' and 'FALSE'

**Comment by nandlalkumar** [comment]
Why i am unable to run binary of restcomm on Ubuntu, able to run successfully on CentOS ver 6 ?
Is there any specific settings needs to be done ? i am just a new learner, trying to understand, how to configure the RestComm from scratch. Please help me.. my email id is nandlalkumar1986@gmail.com

**Comment by peteroyle** [comment]
@nandlalkumar have a look at #385 it might have the solution you need.

**Comment by nandlalkumar** [comment]
Thanks peteroyle, i shall try this one with latest build. Also need one suggestion, i wanted to learn about how restcomm works and wanted to learn through code. i have the source code, can you help me by suggesting from where i should start looking.

Thanks & Regards
Nandlal Kumar

**Comment by peteroyle** [comment]
@nandlalkumar no worries. As you're probably aware, you'll still need to manually apply the change, even to the latest build, since the change hasn't actually been accepted into RestComm master branch yet.

As for developer documentation, I'm not sure what would be best but I would recommend having a look at a post Henrique Rosa made to the RestComm Google Group here: https://groups.google.com/forum/#!topic/restcomm/BgpTrlhtspU specifically the article he links to about RestComm Core Workflows.
