### ISSUE TITLE
RestComm configuration steps for windows

### ISSUE THREAD

**Issue by nandlalkumar** [Mobicents/RestComm#397]
Hi,
I am new to this product, just wanted to try my hands to learn about RestComm. Can anyone help me or provide any documents so that i could configure RestComm on windows and ubuntu environment. Also if i can run the source code through netbeans or eclipse?

**Comment by gvagenas** [comment]
Hi,

You can find documentation and tutorials for how to run and configure Restcomm at http://docs.telestax.com/restcomm-pages/.

Currently we don't have instructions for Windows. If you want to try Restcomm on Windows we strongly suggest using Docker for that, please check https://hub.docker.com/r/gvagenas/restcomm/

George
