### ISSUE TITLE
Unable to call registered client to another registered client using SIP phone  

### ISSUE THREAD

**Issue by nandlalkumar** [Mobicents/RestComm#436]
Hi,

 I am unable to call another registered  client using SIP phone, it rings but unable to listen voice coming from another client. Am i missing any configurations?

Thanks & Regards
Nandlal Kumar

**Comment by leftyb** [comment]
Hi Nandlal,

First please check all your sound settings.
Are you using the same PC for this test. I mean, are you trying to use two different SIP phone instances (each registered to a different user) at the same  PC? This can provoke some sound problems. And finally which SIP soft phone client  you are using?

Regards,
Lefteris

**Comment by nandlalkumar** [comment]
HI Lefteris,
I am using two different softphone instances registered to two different clients. I am using bria for the same.

Regards
Nandlal Kumar

**Comment by leftyb** [comment]
Hi Nandlal, 

Just to clarify, you mean as well that you are not using the same PC, running both bria soft phone instances?  I never used bria (it is for windows, Mac.  I use linux.). Is it possible to use another client like Linphone. I am using LinPhone, without problems.

http://www.linphone.org/

Please check if any errors appear at the log file :  ~RESTCOMM/standalone/log/server.log

Regards

**Comment by nandlalkumar** [comment]
Thanks Lefteris,
I will try linphone, do you have any setting documentation for linphone because once i tried this too but to no avail. I will also try to share log.

Thanks & Regards
Nandlal kumar

**Comment by leftyb** [comment]
Hi @nandlalkumar,

What exactly were the problems you had with linphone? You need to register the linphone with the Restcomm accounts. 

Options-> preferences-> Manage sip accounts -> add.

Your SIP identity : sip:bob@restcomm_ip:5080
Sip Proxy address : <sip:restcomm_ip:5080>
Registration duration : 3600
And the rest options empty. This settings work for me. Please try them, and if you have any problem,
we can discuss them.

Just to repeat, that it is better if you don't mind to use the  RestComm's Google groups so that other users can have access to the issues and solutions.

https://groups.google.com/forum/#!forum/restcomm

Thank you,
Lefteris.

RestComm Contributor.

**Comment by nandlalkumar** [comment]
Thanks  Lefteris.

On Thu, Sep 10, 2015 at 2:42 PM, Lefteris Banos <notifications@github.com>
wrote:

> Hi @nandlalkumar <https://github.com/nandlalkumar>,
>
> What exactly were the problems you had with linphone? You need to register
> the linphone with the Restcomm accounts.
>
> Options-> preferences-> Manage sip accounts -> add.
>
> Your SIP identity : sip:bob@restcomm_ip:5080
> Sip Proxy address : sip:restcomm_ip:5080
> Registration duration : 3600
> And the rest options empty. This settings work for me. Please try them,
> and if you have any problem,
> we can discuss them.
>
> Just to repeat, that it is better if you don't mind to use the RestComm's
> Google groups so that other users can have access to the issues and
> solutions.
>
> https://groups.google.com/forum/#!forum/restcomm
>
> Thank you,
> Lefteris.
>
> RestComm Contributor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mobicents/RestComm/issues/436#issuecomment-139177972>.
>



-- 



Thanks & Regards,
Nandlal Kumar
nandlalkumar1986@gmail.com
