### ISSUE TITLE
Cost doesn't display, Filtering with capabilities doesn't work when searching for a phone number with Nexmo

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#461]
If you try to search for Mobile or SMS numbers only, it doesn't work and display the same list

**Comment by gvagenas** [comment]
The additional field cost breaks backward compatibility if added in the middle of the table structure

**Comment by deruelle** [comment]
no reason, sorry about that. Do you need me to fix anything after your last commit on this ?

**Comment by gvagenas** [comment]
@deruelle I fixed the DB files we use for testsuite. Now that you confirm that this fields can be at the end of the record, I will change the DB schema for HSQLDB and MariaDB and do some more tests to make sure everything is ok

**Comment by gvagenas** [comment]
Will change DB schema and test again
