### ISSUE TITLE
Perform outbound calls to WebRTC clients

### ISSUE THREAD

**Issue by vfpuglia** [Mobicents/RestComm#463]
Attempting to call in which will trigger a dial to a registered client (alice). If alice is registered as a sip device the call will be made and the connection will be established upon answer. But if alice is registered as a webrtc endpoint (olympus) the call will not be presented.

**Comment by deruelle** [comment]
Don't forget to support wss (websockets secure) as transport in addition to ws (websockets) so that it works under secured trusted HTTPS environments

**Comment by deruelle** [comment]
Was there a Pull Request for this ? Is it merged to master yet ?

**Comment by gvagenas** [comment]
Works with XMS, problem only with MMS (MMS issue https://github.com/Mobicents/mediaserver/issues/50)
