### ISSUE TITLE
Admin UI Fails to login on HTTPS

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#478]
the code in some place have http hard coded so it can connect to RestComm is RestComm is running on HTTPS

**Comment by deruelle** [comment]
located in restcomm-management.war/resources/js/services.js and restcomm-management.war/resources/js/restcommApps/appManager.js

**Comment by otsakir** [comment]
There are hardcoded uses of http:// inside services and used for retrieving the account (login). appManager.js hardcoded uses of http:// are related to retrieving apps from apps.restcomm.com which is something different. 

I've created another issue for that: #519

**Comment by deruelle** [comment]
It seems there is still an http hardcoded place at https://github.com/Mobicents/RestComm/blob/45ab324a561a7493a7b1ecd9c887d1d3719778f8/restcomm/restcomm.ui/src/main/webapp/resources/js/restcommApps/appManager.js#L269 that you missed ?

**Comment by otsakir** [comment]
@deruelle , this url points to apps.restcomm.com which we still access over http until they install the official restcomm certificates there.
