### ISSUE TITLE
Toggle SSL verification policy using a configuration flag

### ISSUE THREAD

**Issue by otsakir** [Mobicents/RestComm#485]
Making https requests from Restcomm/RVD is often prevented when servers don't use certificates signed from a welknown CAs. A configuration flag can be used to toggle between a strict/loose SSL behaviour.

In *loose* mode https connections to untrusted sites will be allowed while in *strict* will not. 

A further improvement could be to define trusted hostnames in the configuration file so that the administrator can easily define which hosts he trusts.

Separate implementation should be done for RVD and Restcomm.

**Comment by deruelle** [comment]
Moved to Alpha2 as using a valid certificate and keystore made this issue less urgent
