### ISSUE TITLE
Linphone Composing Messages makes Restcomm throw an Exception

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#494]
https://gist.github.com/deruelle/3f68f7d60e268d867099

The Composing messages shouldn't be allowed for now and we should only accept content type including text only

**Comment by deruelle** [comment]
Merged to RaaS

**Comment by gvagenas** [comment]
Also commit https://github.com/RestComm/RestComm-Core/commit/80edab5d63f7ffdcfcf9bdec7c9db92f8600c48d
