### ISSUE TITLE
Calling an outbound number fails

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#504]
When I call from Jitsi to a RestComm (connected to Nexmo) number tied to the application linked here http://www.filedropper.com/showdownload.php/pstnout it fails  
https://gist.github.com/deruelle/827f9a27a4a2b534e2c0

**Comment by gvagenas** [comment]
The NPE you get is because the Outbound Proxy is null. Check the configuration

**Comment by deruelle** [comment]
True, this issue is invalid. Thanks

**Comment by deruelle** [comment]
We may want to put a better error message though

**Comment by gvagenas** [comment]
Right, I will change that
