### ISSUE TITLE
AdminUI HTTPS login fails with mixed content error

### ISSUE THREAD

**Issue by otsakir** [Mobicents/RestComm#518]
Both, firefox and chromium replied with:
```
Blocked loading mixed active content "http://administrator%40company%2Ecom:77f8c12cc7b8f8423e5c38b035249166@instance1.restcomm.com:8443/restcomm/2012-04-24/Accounts.json/administrator@company.com"[
```

**Comment by otsakir** [comment]
The error happens at the client side before making a request to the server.It was observed while testing with latest *.restcomm.com certificate. Maybe, this changes browser's behaviour regarding mixed content.

**Comment by deruelle** [comment]
I think this is due to Issue #478

**Comment by otsakir** [comment]
Ok, i will mark it as duplicate
