### ISSUE TITLE
Fix cyclic reference issue when building Restcomm from source

### ISSUE THREAD

**Issue by croufay** [Mobicents/RestComm#534]
This issue occurs when you build the root project. Individuals SMPP and SMS project build with success.

The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='com.telestax.servlet:restcomm.smpp:7.4.0-SNAPSHOT'}' and 'Vertex{label='com.telestax.servlet:restcomm.sms:7.4.0-SNAPSHOT'}' introduces to cycle in the graph com.telestax.servlet:restcomm.sms:7.4.0-SNAPSHOT --> com.telestax.servlet:restcomm.smpp:7.4.0-SNAPSHOT --> com.telestax.servlet:restcomm.sms:7.4.0-SNAPSHOT -> [Help 1]

**Comment by deruelle** [comment]
I think @croufay fixed that in the latest SMPP PR. Closing issue as invalid
