### ISSUE TITLE
Update jain-sip to support SDP from Chrome 46

### ISSUE THREAD

**Issue by gvagenas** [Mobicents/RestComm#542]
Related issue https://github.com/Mobicents/jain-sip/issues/6

**Comment by gvagenas** [comment]
Cannot reproduce issue when testing with Mobicents Restcomm 7.4.0.710

**Comment by gvagenas** [comment]
Anyway, updated to the latest jain-sip

**Comment by deruelle** [comment]
I'm still seeing this issue after upgrading https://gist.github.com/deruelle/b2bfa69367fdc3715eea
Look at the stack trace it seems like RestComm is using nist-sdp.jar which has not been updated to fix this issue
