### ISSUE TITLE
Restcomm is looping on some calls

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#554]
If Restcomm is authenticating and an Olympus Client is calling a number not registered in restcomm. RestComm goes into a loop of SIP authentication

**Comment by gvagenas** [comment]
Problem is that To header host part is a DNS record, but Restcomm is checking against its IP Address. This if statement turn to FALSE so Restcomm won't proxy out the request but instead will route it to B2BUA helper and thus will create a loop.

**Comment by deruelle** [comment]
Verified the fix is working
