### ISSUE TITLE
AdminUI - Add orderBy "date_created" button at LOGS _ CALLS page.

### ISSUE THREAD

**Issue by leftyb** [Mobicents/RestComm#561]
![image](https://cloud.githubusercontent.com/assets/4802924/10666986/9cbb778e-78dd-11e5-870b-aac1859b6053.png)

![image](https://cloud.githubusercontent.com/assets/4802924/10667041/e4462324-78dd-11e5-91c7-f5b6062a9c6a.png)

**Comment by brainslog** [comment]
I think visually it can be more discrete, that big button doesn't fit very well in the layout. Something more like this:

![rc561-suggestion](https://cloud.githubusercontent.com/assets/8998984/10720442/1eb85f64-7b8f-11e5-8ba1-78f168d6bd7a.png)

WDYT ? What I've used was:
```html
<th class="width-20pc" style="border-bottom: 3px solid #428bca">DATE<span class="pull-right"><i class="fa fa-chevron-up"></i></span></th>

**Comment by leftyb** [comment]
Hi, 
Yes I agree, your proposal is much better.
I will commit your proposal.

Thank you.

**Comment by deruelle** [comment]
We may want to implement this for the rest of the columns as well ie to, from, type, status, duration and cost.

**Comment by leftyb** [comment]
Sure, I will do it for all the columns.

**Comment by deruelle** [comment]
I tested this feature, this doesn't work correctly for me, see snapshots attached 
![screenshot from 2015-11-06 15 43 39](https://cloud.githubusercontent.com/assets/54279/10999593/368dbd2a-849d-11e5-9b75-8bc4f5e85fec.png)
![screenshot from 2015-11-06 15 43 34](https://cloud.githubusercontent.com/assets/54279/10999594/36b575ae-849d-11e5-978f-f5ce4dc54bda.png)
![screenshot from 2015-11-06 15 43 23](https://cloud.githubusercontent.com/assets/54279/10999595/36deeb14-849d-11e5-8b2c-c513db8fcfec.png)
![screenshot from 2015-11-06 15 43 13](https://cloud.githubusercontent.com/assets/54279/10999596/37147e14-849d-11e5-9b9f-10ba5f846d64.png)

**Comment by leftyb** [comment]
Hi Jean,

I will check it again.

Thank you.

**Comment by otsakir** [comment]
@lefty, i'm closing the issue.

**Comment by leftyb** [comment]
@otsakir  sure.
