### ISSUE TITLE
Allow Incoming SMPP Messages to be routed to Restcomm Clients and Restcomm, Number

### ISSUE THREAD

**Issue by croufay** [Mobicents/RestComm#566]
Allow Incoming SMPP Messages to be routed to Restcomm Clients and Restcomm, Number

yes
I noticed a few things
When SMPP is activated
all SMS go through SMPP, no exception
When a message is receive and your forward it to say, Alice, it will use SIP which SMPP intercepts and will try to send it out through the SMPP connection
jean.deruelle 2:00 PM I see
we should probably check if the To is a registered SIP Client
to which we can send to
if not
check if the To is a Number
and then send it through SMPP in that case
charles 2:01 PM that can be done
what about if you want to send it to a locally registered restcomm number like 2222?
jean.deruelle 2:02 PM in that case
check if the To is a registered SIP Number (edited)
after checking if the To is a registered SIP Client
2:03
so
1. check if the To is a registered SIP Client, then send it to registered SIP Client (edited)
2. check if the To is a registered DID Number, then send it to Registered DID Number (edited)
3. checking if the To is a Phone Number  and send it through SMPP
charles 2:04 PM ok,
jean.deruelle 2:04 PM I just edited my messages above
to make them clearer
charles 2:04 PM let me create an issue for that

**Comment by deruelle** [comment]
@croufay Any luck on tackling those issues yet ?

**Comment by croufay** [comment]
@deruelle 

After further testing, I noticed that sending SMS from a none-Restcomm client to a Restcomm client doesn't work.

none-Restcomm -> Restcomm client (Doesn't work) SIP phone
none-Restcomm -> Restcomm client (Doesn't work) Olympus

You can create an RVD app that receives an SMS and then sends the message to a Restcomm client (SIP phone or Olympus) by changing the From to a Restcomm client like alice or bob.

Then the message is received by Olympus or the SIP phone

Will continue on this after 7.4.0 release

**Comment by croufay** [comment]
fixed 

https://github.com/Mobicents/RestComm/commit/1d61db11f974e2a9c9545f32c6d40f7edafb5c38
