### ISSUE TITLE
Provide SSO services for all restcomm tools

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#58]
Found in 7.2.0 candidate.

To reproduce:
1. Login to /restcomm-management
2. Go to Visual Designer
3. See that login is still required

**Comment by otsakir** [comment]
First iteration on SSO for Rerstcomm tools implementation is complete. Further progress can be tracked on sso brach and its child issues.

**Comment by ivelin** [comment]
Yay!

**Comment by abhayani** [comment]
Thumbs up!
