### ISSUE TITLE
Changing the visual name of an app breaks links to numbers

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#60]
Observed in candidate release 7.2.0.

To reproduce:
1. Link a DID to an app
2. Change the app name
3. Call the DID. It will be broken because the URL of the app is now different.

Desired behavior:
1. Either RVD should generate permanent URLs similar to blogs that do not change as the title of the app changes. 
2. Or keep a table of references to old names and redirect to the URL with the new name.
2. Or it should update links with references. This may be tough because the app URL may be linked from remote Restcomm instances.

**Comment by otsakir** [comment]
The issue can be considered a duplicate and will be resolved when #553, #530, #552 and #529 (which form a logical group) are fixed.
