### ISSUE TITLE
Trying to reach some HTTPS URL fail with RVD External Services

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#609]
See https://gist.github.com/deruelle/aed5614daa93b49210b1. This happens with both strict or allowAll ssl-mode

**Comment by otsakir** [comment]
ES rejected sites that had untrusted CA signed certs. Self-signed now work fine. For a clearer implementation of ssl-mode options see #615 .

**Comment by deruelle** [comment]
Another solution is to use -Dhttps.protocols=TLSv1.1,TLSv1.2 at standalone.conf and make sure the root certificate of the remote site is included in the JDK jre/lib/security/cacerts truststore
