### ISSUE TITLE
Graylog Reconnection error

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#622]
Investigate and solve the error that came up, which  prevents form logging in to the Graylog app after some time has passed for docker launch. (Send a mail to Graylog google group).

**Comment by leftyb** [comment]
I think that we can consider this issue as idle. because, after the fresh initialization did appear again.

**Comment by leftyb** [comment]
The problem persists,  need to have  a closer research on that.

**Comment by leftyb** [comment]
I changed the "Discovery mode" at graylog.conf disabling multicast elasticsearch node discovery.
As recommended here:  http://docs.graylog.org/en/1.2/pages/configuring_es.html

As well I increased the time out time of ping elastcsearch node discovery to 15s from 5s. 

```
# Change the following setting if you are running into problems with timeouts during Elasticsearch cluster discovery.
# The setting is specified in milliseconds, the default is 5000ms (5 seconds).
elasticsearch_cluster_discovery_timeout = 15000

```
Another root of the problem (if the above configurations not work), can be the servers socket "keepalive" mode as stated here [keepalive-error](http://blog.trifork.com/2015/04/08/dealing-with-nodenotavailableexceptions-in-elasticsearch/).  But with the "keepalive" mode after some time the socket is closed from the kerner SO. and as a result graylog cannot communicate with the elasticsearch node.  looks like, once the socket is "opened" again everything  works properly.

**Comment by leftyb** [comment]
Closing the issue. Solved after adding memory to elasticsearch.
