### ISSUE TITLE
Graylog RestComm Docker Image

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#623]
Conclude with the correct configuration of Graylog in terms of Rescomm personalize functional necessities.  ( Safe graylog upgrades, Prevent data loss, disk reusage/log rotation, elastic search configuration, etc)

**Comment by leftyb** [comment]
Closing the issue. Our own, docker graylog repository  is ready. (The only changes can be in case of additional functionalities. e.g Alerting system)
