### ISSUE TITLE
Update Graylog RestComm dashboards

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#625]
Add CPU and Memory Usage Graphs

**Comment by leftyb** [comment]
The Dashboards are ready but there is an issue, with the number representation of Graylog2. E.g. "sip-sessions-created" : 1467, but graylog converts the value to decimal number.

**Comment by leftyb** [comment]
Ok, after consulting with graylog forum, it appears that they use the English representation of the integer numbers, so it is not an problem and everything works properly.
