### ISSUE TITLE
RVD sometimes doesn't save changes to projects 

### ISSUE THREAD

**Issue by desipepova** [Mobicents/RestComm#63]
RVD sometimes doesn't save changes to project .

To reproduce:
- Go to RVD and create new project;
- Create few modules (4-5, include External Services and Assignments in them);
- Save project periodically (after creating each module);
- Go to RVD, log in again and choose your project

When project is bigger than 2-3 modules, some of the changes are not being saved sometimes

Another issue is that when two users (both logged in), are reviewing the app they got different result in their browsers (one of them is seeing the changes made on the project and the other one is not).

Even when opening different browser they may get different preview.

**Comment by otsakir** [comment]
RVD doesn't support collaboration. So when two users work on the same project and they both save, one will overwrite the other's changes. That probably causes the strange behaviour you are experiencing. 

A workaround for this bad UX is described in #274
