### ISSUE TITLE
Supervisor API shows wrong number of registered users

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#633]
On RaaS we have currently 6 registered users but there is no regular REGISTER going on to the server and the OPTION pings from RestComm to them failed and timed out, so it seems the number of registered users reported is wrong

**Comment by gvagenas** [comment]
Work in progress commit: https://github.com/Mobicents/RestComm/commit/33dd3427ddde2faf0716be28c681da5d8b52de5d

**Comment by gvagenas** [comment]
To properly solve this issue, issue #27 needs to be closed also. 
See the comments on issue #27
