### ISSUE TITLE
Some RaaS accounts do not allow Olympus calls to default 1234 IVR extension

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#649]
My RaaS account doesn't have this issue, but Jason's did. See video.

**Comment by ivelin** [comment]
https://youtu.be/ZdNRbW4-kGY

**Comment by leftyb** [comment]
To test the issue I created two new users on Cloud server:

username: issue1 , passwd: 1234,
username: issue2, passwd:1234.

I called from both users using Jitsi, +1234 and RestComm responded properly.
No errors appeared at the logs and ended properly. 

*need to be tested on olympus. @gvagenas  can you please test it when you have the time?
(I am having some issues with webrtc, although everything is good at restcomm logs i dont have sound, I thing that maybe a NAT issue with my router).

**Comment by gvagenas** [comment]
Tested with Olympus on Chrome and both accounts can call 1234/1235 etc. 

As far as I can see from the youtube video, Jason is using Firefox for which there is a known issue and the WebRTC calls will fail. Chrome should be used.

I will close the issue for now.
