### ISSUE TITLE
RVD/ES Support JSON requests

### ISSUE THREAD

**Issue by otsakir** [Mobicents/RestComm#68]
For external services that only accept JSON parameters ES control should be able to build a JSON formatted request. 

This is a low priority issue

**Comment by ivelin** [comment]
That would certainly help. We would be able to build Zapier package for Restcomm, like the one for WordPress Gravity Forms:

![screen shot 2015-03-29 at 10 51 39 am](https://cloud.githubusercontent.com/assets/2234901/6946361/60effaea-d865-11e4-8ad7-6e1188655510.png)
![screen shot 2015-03-29 at 10 53 05 am](https://cloud.githubusercontent.com/assets/2234901/6946397/88c4d48c-d865-11e4-8ce6-2e4e6e44f87b.png)

**Comment by scottbarstow** [comment]
Ideally, as we've talked about, we would be able to create POST body params in addition to url params.

**Comment by ivelin** [comment]
@otsakir can you please prioritize this issue, so Scott can advance with his TADHack project. Thank you!

**Comment by scottbarstow** [comment]
What I would expect is to be able to something like:

{
   "myvalue": "your message was $coreBody",
   "from": $coreFrom
}

etc.

**Comment by otsakir** [comment]
Ok @scottbarstow , got it! 

@ivelin i will prioritize the issue.

**Comment by ivelin** [comment]
@otsakir is the code committed? Don't see it in the log of this issue.

**Comment by otsakir** [comment]
oops! there it's in a separate branch. Let me do the merge...

**Comment by scottbarstow** [comment]
I'm not seeing this change yet in the master build.  Is it in?

**Comment by otsakir** [comment]
It should be. You need to press the gear icon under the "Add Service parameter" button, switch the method to "POST". A textarea will appear. You can add your request body there. Also, notice the new "Content-Type" to "json".
