### ISSUE TITLE
RestComm doesn't send the SMS over SMPP in case a real number is specified

### ISSUE THREAD

**Issue by deruelle** [Mobicents/RestComm#696]
When using the app attached and placing a call via Olympus to it, the SMS is not sent over SMPP but tries to be routed over SIP MESSAGE instead of SMPP, see logs at https://gist.github.com/deruelle/a2450a5155cc9677b86d

![screenshot from 2015-12-02 12 04 13](https://cloud.githubusercontent.com/assets/54279/11529354/d5d48e32-98ec-11e5-97be-f96c49a09066.png)

**Comment by croufay** [comment]
https://github.com/Mobicents/RestComm/commit/bd76e9eff3f10c7fa876d239aa93a6c86a5574c4
