### ISSUE TITLE
Enable outbound calls to WebRTC clients

### ISSUE THREAD

**Issue by hrosa** [Mobicents/RestComm#698]
Enable outbound calls to WebRTC clients.

This issue was disabled on master because of issues detected on Mobicents MS side.

We need to enable it to test against Dialogic XMS.

**Comment by hrosa** [comment]
Could establish call between two WebRTC clients, but audio is flowing one-audio.
The caller can hear the callee, but the callee hears no audio.

Trace of the call can be found [here] (https://gist.github.com/hrosa/8346602e9969c32311ac)

**Comment by hrosa** [comment]
Waiting on Dialogic team to debug the driver and provide more information.

**Comment by RomanDS** [comment]
How can I reproduce this issue? We will need to collect wireshark traces from XMS for that scenario.

**Comment by hrosa** [comment]
@RomanDS Here are the steps to reproduce:

1. Download binary from [RestComm XMS CI job] (https://mobicents.ci.cloudbees.com/view/RestComm/job/RestComm-XMS/7).
2. Configure to work against Dialogic XMS and launch.
3. Register WebRTC client "alice"
3. With a second client, dial the demo app +1238 (Dial -> Client "alice").
4. The WebRTC client "alice" should start ringing. Accept the audio call.

**Comment by hrosa** [comment]
Found the reason for the one-way audio on callee side.

The SDP offer generated by the XMS for the outbound call included an m=video stream. Chrome behaves in a way that, when video is negotiated, no audio will be played until first video frame is received.

Because the caller was not sending video, Chrome would not render audio on the callee side.
