### ISSUE TITLE
Url attribute for <dial><client> noun fails with application relative value

### ISSUE THREAD

**Issue by otsakir** [Mobicents/RestComm#711]
This RCML fails:
```
<Response><Say>welcome to dial. You will be connected to bob</Say><Dial action="controller?target=start.step2.actionhandler"><Client url="controller?target=module1">bob</Client></Dial></Response>
```
with the following error:

11:47:02,355 ERROR [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-445) java.net.MalformedURLException: no protocol: controller?target=module1: org.mobicents.servlet.restcomm.fsm.TransitionFailedException: java.net.MalformedURLException: no protocol: controller?target=module1
        at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:89) [restcomm.commons-7.5.0.1211.jar:]
        at org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter.onBridgeStateChanged(VoiceInterpreter.java:843) [restcomm.interpreter-7.5.0.1211.jar:]
        at org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter.onReceive(VoiceInterpreter.java:826) [restcomm.interpreter-7.5.0.1211.jar:]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
Caused by: java.net.MalformedURLException: no protocol: controller?target=module1
        at java.net.URL.<init>(URL.java:585) [rt.jar:1.7.0_79]
        at java.net.URL.<init>(URL.java:482) [rt.jar:1.7.0_79]
        at java.net.URL.<init>(URL.java:431) [rt.jar:1.7.0_79]
        at org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter$Bridging.buildSubVoiceInterpreter(VoiceInterpreter.java:2253) [restcomm.interpreter-7.5.0.1211.jar:]
        at org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter$Bridging.execute(VoiceInterpreter.java:2281) [restcomm.interpreter-7.5.0.1211.jar:]
        at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:87) [restcomm.commons-7.5.0.1211.jar:]
        ... 12 more

**Comment by otsakir** [comment]
Still having issues. Tried with static RCML files:

welcome.xml
```
<Response>
	<Say>welcome to test dial client test. You will be connected to bob with screening</Say>
	<Dial>
		<Client url="screening.xml">bob</Client>
	</Dial>
</Response>
```

screening.xml
```
<Response>
	<Say>Hi bob. Someone wants to talk to you</Say>
</Response>
```
and got this in the logs:

<code>
17:01:02,232 INFO  [org.mobicents.servlet.restcomm.interpreter.SubVoiceInterpreter] (RestComm-akka.actor.default-dispatcher-152)  ********** SubVoiceInterpreter's Current State: downloading rcml
17:01:02,234 INFO  [org.mobicents.servlet.restcomm.interpreter.SubVoiceInterpreter] (RestComm-akka.actor.default-dispatcher-152)  ********** SubVoiceInterpreter's Processing Message: org.mobicents.servlet.restcomm.http.client.DownloaderResponse
17:01:02,237 ERROR [org.mobicents.servlet.restcomm.interpreter.SubVoiceInterpreter] (RestComm-akka.actor.default-dispatcher-152) There was a problem during creation of parser for xml: 
<!DOCTYPE html>
<html ng-app="rcApp">
    <head>
        <title>RestComm</title>

        <link rel="icon" type="image/png" href="resources/img/favicon.png">
        <link rel="stylesheet" href="lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="lib/bootstrap-multiselect/css/bootstrap-multiselect.css" />
        <link rel="stylesheet" href="lib/animate/animate.css" />
        <link rel="stylesheet" href="lib/world-flags/stylesheets/flags16.css" />
        <link rel="stylesheet" href="lib/nvd3/nv.d3.css">
        <link rel="stylesheet" href="resources/css/restcomm.css" />
        <link rel="stylesheet" href="resources/css/datepicker.css" />
        <style type="text/css">

            .sidebar-nav {
                padding: 9px 0;
            }

                /* Sticky footer styles
                -------------------------------------------------- */

            html,
            body {
                height: 100%;
                /* The html and body elements cannot have any padding or margin. */
            }

                /* Wrapper for page content to push down footer */
            #wrap {
                min-height: 100%;
                height: auto !important;
                height: 100%;
                /* Negative indent footer by it's height */
                margin: 0 auto -75px;
            }

                /* Set the fixed height of the footer here */
            #push,
            #footer {
                height: 75px;
            }
            #footer {
            }

                /* Custom page CSS
                -------------------------------------------------- */
                /* Not required for template or sticky footer method. */

            .container {
                width: auto;
                max-width: 960px;
            }

            #wrap > .container-fluid {
                padding-top: 60px;
            }
            #wrap > .container {
                padding-top: 60px;
            }
            .container .credit {
                margin: 20px 0;
            }

                /* Lastly, apply responsive CSS fixes as necessary */
            @media (max-width: 767px) {
                #footer {
                    margin-left: -20px;
                    margin-right: -20px;
                    padding-left: 20px;
                    padding-right: 20px;
                }
                #wrap > .container-fluid {
                    padding-top: 0px;
                }
            }

            @media (max-width: 980px) {
                /* Enable use of floated navbar text */
                .navbar-text.pull-right {
                    float: none;
                    padding-left: 5px;
                    padding-right: 5px;
                }
                #wrap > .container-fluid {
                    padding-top: 0px;
                }
            }


        </style>

        
        <script type="text/javascript" src="lib/jquery/jquery.js"></script>
        <script type="text/javascript" src="lib/file-upload/angular-file-upload-shim.min.js"></script>
        <script type="text/javascript" src="lib/angular/angular.min.js"></script>
        <script type="text/javascript" src="lib/file-upload/angular-file-upload.min.js"></script>
        <script type="text/javascript" src="lib/angular-route/angular-route.min.js"></script>
        <script type="text/javascript" src="lib/angular-resource/angular-resource.min.js"></script>
        <script type="text/javascript" src="lib/angular/angular-datepicker.js"></script>
        <script type="text/javascript" src="lib/underscore/underscore.js"></script>
        <script type="text/javascript" src="lib/underscore/underscore.string.js"></script>
        <script type="text/javascript" src="lib/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="lib/bootstrap-multiselect/js/bootstrap-multiselect.js"></script>
        <script type="text/javascript" src="lib/angular-bootstrap/ui-bootstrap-tpls.js"></script>
        <script type="text/javascript" src="lib/ng-password-strength/js/ng-password-strength.js"></script>
        <script type="text/javascript" src="lib/http-auth-interceptor/http-auth-interceptor.js"></script>
        <script type="text/javascript" src="lib/angular-sanitize/angular-sanitize.min.js"></script>
		<script type="text/javascript" src="lib/d3/d3.min.js"></script>
        <script type="text/javascript" src="lib/nvd3/nv.d3.js"></script>
        <script type="text/javascript" src="lib/angular-nvd3/angular-nvd3.js"></script>

        <script type="text/javascript" src="resources/js/restcomm.js"></script>
        <script type="text/javascript" src="resources/js/controllers.js"></script>
        <script type="text/javascript" src="resources/js/controllers/global.js"></script>
        <script type="text/javascript" src="resources/js/controllers/navbar.js"></script>
        <script type="text/javascript" src="resources/js/controllers/login.js"></script>
        <script type="text/javascript" src="resources/js/controllers/dashboard.js"></script>
        <script type="text/javascript" src="resources/js/controllers/logs-calls.js"></script>
        <script type="text/javascript" src="resources/js/controllers/logs-messages.js"></script>
        <script type="text/javascript" src="resources/js/controllers/logs-notifications.js"></script>
        <script type="text/javascript" src="resources/js/controllers/logs-recordings.js"></script>
        <script type="text/javascript" src="resources/js/controllers/logs-transcriptions.js"></script>
        <script type="text/javascript" src="resources/js/controllers/numbers-incoming.js"></script>
        <script type="text/javascript" src="resources/js/controllers/numbers-outgoing.js"></script>
        <script type="text/javascript" src="resources/js/controllers/numbers-sip-clients.js"></script>        
        <script type="text/javascript" src="resources/js/controllers/events.js"></script>
        <script type="text/javascript" src="resources/js/services.js"></script>
        <script type="text/javascript" src="resources/js/filters.js"></script>
        <script type="text/javascript" src="resources/js/directives.js"></script>
        
        
        <script type="text/javascript" src="resources/js/restcommApps/Module.js"></script>
        <script type="text/javascript" src="resources/js/restcommApps/appManager.js"></script>
        <script type="text/javascript" src="resources/js/restcommApps/appConfig.js"></script>
        <script type="text/javascript" src="resources/js/restcommApps/services.js"></script>
        
    </head>
    <body>
        <div id="wrap">
            <div class="notifications-wrapper" data-ng-show="notifications.data.length > 0">
                <div ng-repeat="notification in notifications.data">
                    <div class="alert alert-{{notification.type}}" style="padding: 9px; margin-bottom: 0;" ng-click="notifications.remove($index)">
                        <span ng-show="notification.type == 'success'"><i class="fa fa-check-circle"></i> </span>
                        <span ng-show="notification.type == 'info'"><i class="fa fa-info-circle"></i></span>
                        <span ng-show="notification.type == 'danger'"><i class="fa fa-exclamation-circle"></i></span>
                        <span ng-show="notification.type == 'warning'"><i class="fa fa-warning"></i></span>
                        <strong>{{notification.header}}</strong> {{notification.message}}
                    </div>
                </div>
            </div>
            <div class="navbar navbar-inverse navbar-fixed-top" role="navigation" ng-controller="MenuCtrl">
                <div class="container-fluid">
                        <div class="navbar-header">
                            <span class="navbar-brand"><img src="resources/img/telestax-logo-dark.png" class="navbar-telestax" /> <img src="resources/img/restcomm-logo.png" class="navbar-restcomm" /> RESTCOMM</span>
                        </div>
                        <i class="fa fa-info-circle pull-right text-danger clickable" style="padding-top: 12px;" ng-click="showAboutModal()"></i>
                        <div class="navbar-collapse collapse">
                            <div ng-show="auth.isLoggedIn()">
                            <ul class="nav navbar-nav">
                                <li><a> </a></li>
                                <li><a ng-href="#/dashboard"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                                <li class="divider-vertical"></li>
                                <li><a ng-href="#/numbers"><i class="fa fa-phone"></i> Numbers</a></li>
                                <li class="divider-vertical"></li>
                                <li><a ng-href="#/logs"><i class="fa fa-file-text-o"></i> Logs</a></li>
                                <li class="divider-vertical"></li>
                                
                                
                                <li><a ng-href="/restcomm-rvd/" target="_blank"><i class="fa fa-pencil"></i> Visual Designer</a></li>
                                <li class="divider-vertical"></li>
                                <li><a ng-href="#/ras/" ><i class="fa fa-shopping-cart"></i> Restcomm Apps</a></li>
                                <li class="divider-vertical"></li>  
                                
                                
                                
                                
                            </ul>
                            
                            <ul class="nav navbar-nav pull-right">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ auth.getLoggedUser() }} <b class="caret"></b></a>
                                    <ul id="rightMenu" class="dropdown-menu pull-right">
                                        <li><a href="#/profile/{{ auth.getAccountSid() }}"><i class="fa fa-cog"></i> Account Settings</a></li>
                                        <li class="divider"></li>
                                        <li class="navbar-header text-muted" style="margin-left: 10px;">Sub Accounts</li>
                                        <li ng-repeat="account in accountsList" ng-hide="account.sid == auth.getAccountSid()"><a href="#"><i ng-class="account.type == 'Full' ? 'fa fa-suitcase' : 'fa fa-code'"> </i> {{account.friendly_name}}</a></li>
                                        <li class="disabled"><a href="#"></a> </li>
                                        <li class="disabled"><a href="#"></a> </li>
                                        <li class=""><a href="#" onclick="return false;" ng-click="showRegisterAccountModal();"><i class="fa fa-plus"></i> Create New Account...</a> </li>
                                        <li class="divider"></li>
                                        <li><a href="#/login" ng-click="logout()"><i class="fa fa-sign-out"></i> Sign Out</a></li>
                                    </ul>
                                </li>
                            </ul>
                            </div>
                        </div>
                    </div>
            </div>
            <div class="container" ng-view>
            </div>
            <div id="push"></div>
            <div id="footer" class="opacity50">
                <div class="container">
                    <h4 class="pull-right">POWERED BY RESTCOMM <small>(c) 2013 TeleStax </small></h4>
                </div>
            </div>
        </div>
        <div ng-controller="EventsCtrl"></div>
    </body>
</html>

Exception is: java.io.IOException: com.ctc.wstx.exc.WstxParsingException: Unexpected close tag </head>; expected </link>.
 at [row,col {unknown-source}]: [139,10]
17:01:02,240 ERROR [akka.actor.ActorCell] (RestComm-akka.actor.default-dispatcher-152) error while processing Create(1727890385): 07080e8c-3ca7-410a-aa03-a1ff201a6f2dakka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:170) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.create(ActorCell.scala:496) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:351) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:256) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:211) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
Caused by: 8dc5f17e-b4f7-4312-9b8a-3d93207d9b42akka.actor.ActorInitializationException: Actor instance passed to actorOf can't be 'null'
	at akka.actor.ActorInitializationException$.apply(Actor.scala:170) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.newActor(ActorCell.scala:464) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.create(ActorCell.scala:479) [akka-actor_2.10-2.1.2.jar:]
	... 8 more

17:01:04,095 INFO  [org.mobicents.servlet.sip.core.session.SipSessionImpl] (MSS-Executor-Thread-4) Invalidating the sip session (76a49d9f;2fde9e9b89979e18c1368512a2190324@0:0:0:0:0:0:0:0;8d3b1589;RestComm)
17:01:04,095 INFO  [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (MSS-Executor-Thread-4) Invalidating the following sip application session 8d3b1589;RestComm
17:01:04,096 INFO  [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (MSS-Executor-Thread-4) The following sip application session 8d3b1589;RestComm has been invalidated
17:01:08,242 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-156)  ********** VoiceInterpreter's akka://RestComm/user/$C Current State: playing
17:01:08,243 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-156)  ********** VoiceInterpreter's akka://RestComm/user/$C Processing Message: akka.actor.ReceiveTimeout$
17:01:10,843 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-150)  ********** VoiceInterpreter's akka://RestComm/user/$p Current State: playing
17:01:10,844 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-150)  ********** VoiceInterpreter's akka://RestComm/user/$p Processing Message: akka.actor.ReceiveTimeout$
17:01:10,865 INFO  [gov.nist.javax.sip.stack.UDPMessageChannel] (Mobicents-SIP-Servlets-UDPMessageChannelThread-194) Setting SIPMessage peerPacketSource to: /192.168.1.39:5060
17:01:10,866 INFO  [gov.nist.javax.sip.stack.SIPTransactionStack] (Mobicents-SIP-Servlets-UDPMessageChannelThread-194) <message
from="192.168.1.39:5060" 
to="192.168.1.39:5080" 
time="1449586870863"
isSender="false" 
transactionId="z9hg4bkpjc0eeae0b-8bee-49ca-b326-cb633f767da4" 
callId="5152787cb5d18efe7e60c130d899a244@192.168.1.39" 
firstLine="BYE sip:bob@192.168.1.39:5080 SIP/2.0" 
>
<![CDATA[BYE sip:bob@192.168.1.39:5080 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.39:5060;rport=5060;branch=z9hG4bKPjc0eeae0b-8bee-49ca-b326-cb633f767da4;received=192.168.1.39
Max-Forwards: 70
From: <sip:bob@192.168.1.39>;tag=39dac4b1-ef7a-4288-b734-6410c0cbc072
To: "bob" <sip:bob@192.168.1.39>;tag=17412682_f78837c1_57a5b08a_1aef8f44
Call-ID: 5152787cb5d18efe7e60c130d899a244@192.168.1.39
CSeq: 27073 BYE
Contact: <sip:bob@192.168.1.39:5060>
Content-Length: 0

]]>
</message>

17:01:10,869 INFO  [org.mobicents.servlet.restcomm.telephony.util.B2BUAHelper] (RestComm-akka.actor.default-dispatcher-150) SIP SESSION is NULL
17:01:10,870 INFO  [org.mobicents.servlet.restcomm.telephony.Call] (RestComm-akka.actor.default-dispatcher-156) ********** Call's akka://RestComm/user/$pb Current State: "in progress
17:01:10,870 INFO  [org.mobicents.servlet.restcomm.telephony.Call] (RestComm-akka.actor.default-dispatcher-156) ********** Call akka://RestComm/user/$pb Processing Message: "org.mobicents.servlet.sip.message.Servlet3SipServletRequestImpl sender : akka://RestComm/user/$f
17:01:10,871 INFO  [gov.nist.javax.sip.stack.SIPTransactionStack] (RestComm-akka.actor.default-dispatcher-150) <message
from="192.168.1.39:5080" 
to="192.168.1.39:5060" 
time="1449586870871"
isSender="true" 
transactionId="z9hg4bkpjc0eeae0b-8bee-49ca-b326-cb633f767da4" 
callId="5152787cb5d18efe7e60c130d899a244@192.168.1.39" 
firstLine="SIP/2.0 200 OK" 
>
<![CDATA[SIP/2.0 200 OK
To: "bob" <sip:bob@192.168.1.39>;tag=17412682_f78837c1_57a5b08a_1aef8f44
Via: SIP/2.0/UDP 192.168.1.39:5060;rport=5060;branch=z9hG4bKPjc0eeae0b-8bee-49ca-b326-cb633f767da4;received=192.168.1.39
CSeq: 27073 BYE
Call-ID: 5152787cb5d18efe7e60c130d899a244@192.168.1.39
From: <sip:bob@192.168.1.39>;tag=39dac4b1-ef7a-4288-b734-6410c0cbc072
Server: TelScale Restcomm MAJOR_VERSION_NUMBER.BUILD_NUMBER
Content-Length: 0

]]>
</message>

17:01:10,872 INFO  [org.mobicents.servlet.restcomm.mscontrol.mgcp.MmsCallController] (RestComm-akka.actor.default-dispatcher-156) ********** Call Controller Current State: "active
17:01:10,873 INFO  [org.mobicents.servlet.restcomm.mscontrol.mgcp.MmsCallController] (RestComm-akka.actor.default-dispatcher-156) ********** Call Controller Processing Message: "org.mobicents.servlet.restcomm.mscontrol.messages.CloseMediaSession sender : class akka.actor.RepointableActorRef
17:01:10,874 INFO  [org.mobicents.servlet.restcomm.mgcp.Connection] (RestComm-akka.actor.default-dispatcher-156)  ********** Connection Current State: open
17:01:10,874 INFO  [org.mobicents.servlet.restcomm.mgcp.Connection] (RestComm-akka.actor.default-dispatcher-156)  ********** Connection Processing Message: org.mobicents.servlet.restcomm.mgcp.CloseConnection
17:01:10,889 INFO  [org.mobicents.servlet.restcomm.mgcp.Connection] (RestComm-akka.actor.default-dispatcher-154)  ********** Connection Current State: closing
17:01:10,889 INFO  [org.mobicents.servlet.restcomm.mgcp.Connection] (RestComm-akka.actor.default-dispatcher-154)  ********** Connection Processing Message: jain.protocol.ip.mgcp.message.DeleteConnectionResponse
17:01:10,890 INFO  [org.mobicents.servlet.restcomm.mscontrol.mgcp.MmsCallController] (RestComm-akka.actor.default-dispatcher-154) ********** Call Controller Current State: "closing connection
17:01:10,890 INFO  [org.mobicents.servlet.restcomm.mscontrol.mgcp.MmsCallController] (RestComm-akka.actor.default-dispatcher-154) ********** Call Controller Processing Message: "org.mobicents.servlet.restcomm.mgcp.ConnectionStateChanged sender : class akka.actor.LocalActorRef
17:01:10,890 INFO  [org.mobicents.servlet.restcomm.mscontrol.mgcp.MmsCallController] (RestComm-akka.actor.default-dispatcher-154) De-activating Call Controller
17:01:10,890 INFO  [org.mobicents.servlet.sip.core.session.SipSessionImpl] (RestComm-akka.actor.default-dispatcher-150) Invalidating the sip session (17412682_f78837c1_57a5b08a_1aef8f44;5152787cb5d18efe7e60c130d899a244@192.168.1.39;1aef8f44;RestComm)
17:01:10,891 INFO  [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (RestComm-akka.actor.default-dispatcher-150) Invalidating the following sip application session 1aef8f44;RestComm
17:01:10,891 INFO  [org.mobicents.servlet.restcomm.mscontrol.mgcp.MmsCallController] (RestComm-akka.actor.default-dispatcher-154) Call Controller: akka://RestComm/user/$qb about to stop bridge endpoint: akka://RestComm/user/$b/$Hb
17:01:10,891 INFO  [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (RestComm-akka.actor.default-dispatcher-150) The following sip application session 1aef8f44;RestComm has been invalidated
17:01:10,891 INFO  [org.mobicents.servlet.restcomm.mscontrol.mgcp.MgcpMediaGroup] (RestComm-akka.actor.default-dispatcher-154) ********** Media Group akka://RestComm/user/$qb/$a Current State: "active
17:01:10,892 INFO  [org.mobicents.servlet.restcomm.mscontrol.mgcp.MgcpMediaGroup] (RestComm-akka.actor.default-dispatcher-154) ********** Media Group akka://RestComm/user/$qb/$a Processing Message: "org.mobicents.servlet.restcomm.patterns.StopObserving sender : class akka.actor.RepointableActorRef
17:01:10,896 INFO  [org.mobicents.servlet.restcomm.mgcp.MediaGateway] (RestComm-akka.actor.default-dispatcher-154) Gateway: akka://RestComm/user/$b about to stop endpoint path: akka://RestComm/user/$b/$Hb isTerminated: false sender: akka://RestComm/user/$qb
17:01:10,896 INFO  [org.mobicents.servlet.restcomm.mscontrol.mgcp.MgcpMediaGroup] (RestComm-akka.actor.default-dispatcher-154) ********** Media Group akka://RestComm/user/$qb/$a Current State: "active
17:01:10,897 INFO  [org.mobicents.servlet.restcomm.mscontrol.mgcp.MgcpMediaGroup] (RestComm-akka.actor.default-dispatcher-146) ********** Media Group akka://RestComm/user/$qb/$a Processing Message: "org.mobicents.servlet.restcomm.mscontrol.messages.StopMediaGroup sender : class akka.actor.DeadLetterActorRef
17:01:10,897 INFO  [org.mobicents.servlet.restcomm.mgcp.BridgeEndpoint] (RestComm-akka.actor.default-dispatcher-146) Bridge: akka://RestComm/user/$b/$Hb bridge id: mobicents/bridge/20@192.168.1.39:2427 at postStop, sender: akka://RestComm/deadLetters
17:01:10,897 INFO  [org.mobicents.servlet.restcomm.telephony.Call] (RestComm-akka.actor.default-dispatcher-146) ********** Call's akka://RestComm/user/$pb Current State: "stopping
17:01:10,898 INFO  [org.mobicents.servlet.restcomm.telephony.Call] (RestComm-akka.actor.default-dispatcher-146) ********** Call akka://RestComm/user/$pb Processing Message: "org.mobicents.servlet.restcomm.mscontrol.messages.MediaServerControllerStateChanged sender : akka://RestComm/user/$qb
17:01:10,898 INFO  [org.mobicents.servlet.restcomm.telephony.Call] (RestComm-akka.actor.default-dispatcher-146) Completing Call
17:01:10,898 INFO  [org.mobicents.servlet.restcomm.interpreter.SubVoiceInterpreter] (RestComm-akka.actor.default-dispatcher-146)  ********** SubVoiceInterpreter's Current State: ready
17:01:10,898 INFO  [org.mobicents.servlet.restcomm.interpreter.SubVoiceInterpreter] (RestComm-akka.actor.default-dispatcher-146)  ********** SubVoiceInterpreter's Processing Message: org.mobicents.servlet.restcomm.telephony.CallStateChanged
17:01:10,899 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-146)  ********** VoiceInterpreter's akka://RestComm/user/$mb Current State: bridging
17:01:10,899 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-146)  ********** VoiceInterpreter's akka://RestComm/user/$mb Processing Message: org.mobicents.servlet.restcomm.telephony.CallStateChanged
17:01:10,900 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-146) call state changed. New call state: completed
17:01:10,900 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-146) Action attribute is null.
17:01:10,900 INFO  [org.mobicents.servlet.restcomm.telephony.Call] (RestComm-akka.actor.default-dispatcher-146) ********** Call's akka://RestComm/user/$nb Current State: "in progress
17:01:10,901 INFO  [org.mobicents.servlet.restcomm.telephony.Call] (RestComm-akka.actor.default-dispatcher-146) ********** Call akka://RestComm/user/$nb Processing Message: "org.mobicents.servlet.restcomm.telephony.Hangup sender : akka://RestComm/user/$mb
17:01:10,901 INFO  [org.mobicents.servlet.restcomm.telephony.Bridge] (RestComm-akka.actor.default-dispatcher-146) ********** Bridge akka://RestComm/user/$e/$h State: "ready
17:01:10,902 INFO  [org.mobicents.servlet.restcomm.telephony.Bridge] (RestComm-akka.actor.default-dispatcher-146) ********** Bridge akka://RestComm/user/$e/$h Processing: "org.mobicents.servlet.restcomm.telephony.StopBridge Sender: akka://RestComm/user/$mb
17:01:10,902 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-146)  ********** VoiceInterpreter's akka://RestComm/user/$mb Current State: finish dialing
17:01:10,902 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-146)  ********** VoiceInterpreter's akka://RestComm/user/$mb Processing Message: org.mobicents.servlet.restcomm.interpreter.rcml.End
17:01:10,903 ERROR [org.mobicents.servlet.restcomm.telephony.Bridge] (RestComm-akka.actor.default-dispatcher-146) java.lang.NullPointerException: org.mobicents.servlet.restcomm.fsm.TransitionFailedException: java.lang.NullPointerException
	at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:89) [restcomm.commons-7.5.0-SNAPSHOT.jar:]
	at org.mobicents.servlet.restcomm.telephony.Bridge.onStopBridge(Bridge.java:233) [restcomm.telephony-7.5.0-SNAPSHOT.jar:]
	at org.mobicents.servlet.restcomm.telephony.Bridge.onReceive(Bridge.java:161) [restcomm.telephony-7.5.0-SNAPSHOT.jar:]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
Caused by: java.lang.NullPointerException
	at org.mobicents.servlet.restcomm.telephony.Bridge$Stopping.execute(Bridge.java:348) [restcomm.telephony-7.5.0-SNAPSHOT.jar:]
	at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:87) [restcomm.commons-7.5.0-SNAPSHOT.jar:]
	... 12 more

17:01:10,916 INFO  [org.mobicents.servlet.restcomm.mscontrol.mgcp.MgcpMediaGroup] (RestComm-akka.actor.default-dispatcher-146) MediaGroup :akka://RestComm/user/$qb/$a at postStop, about to stop ivr endpoint :akka://RestComm/user/$b/$Ib

</code>

**Comment by gvagenas** [comment]
@otsakir Just pushed a fix for the SubVoiceInterpreter, responsible for the screening url.

Also make sure that the screening.xml provides the proper relative path if you use a wav file and Play.
Restcomm resolves relative paths by using the localhost address and port, but it doesn't try to resolve the path. You have to provide the proper path.

If you use a Play verb the proper relative path should be:
/restcomm/audio/MyAudio.wav.

When using Say there is nothing special you need to pay attention.

Please test and try again
