### ISSUE TITLE
Multi-tenancy support

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#87]
Currently there is no API to create a new top level account.
I had a conversation with George and it turned out that all accounts share the same assets.
For example account A can see all DIDs of account B and the other way around.
The following behavior should be implemented:
Peer level accounts should not see any of the other account's assets.
2. Parent accounts should see all of a children's account assets.
3. A sub-account/child should not see the parent assets

**Comment by ivelin** [comment]
Another issues came up that is related to multi-tenancy. Since all users login with the same ID and share assets (numbers and apps), over time the UX becomes a mess. Noone knows which apps and numbers are stale and can be removed. 

Each user should have their own login and assets to manage. Only admins should be able to see and manage apps and numbers across users, but it should be clear which assets belong to whom.

**Comment by ivelin** [comment]
Another issues came up that is related to multi-tenancy. Since all users login with the same ID and share assets (numbers and apps), over time the UX becomes a mess. Noone knows which apps and numbers are stale and can be removed. 

Each user should have their own login and assets to manage. Only admins should be able to see and manage apps and numbers across users, but it should be clear which assets belong to whom.

**Comment by deruelle** [comment]
It seems the isolation is working in a better way for the newest version where a sub account can't see the parent DID but the applications are still visible to everyone. It seems this depends on https://github.com/Mobicents/RestComm/issues/4 to be completed in both RestComm and RVD

**Comment by ivelin** [comment]
Thanks for the update @deruelle . Its important to close this issue for the SaaS launch.

**Comment by otsakir** [comment]
Yes, the application notion should be supported by core restcomm. Currently we are treating applications as URLs. It's quite limiting.

@ivelin , regarding multi-tenancy support the issues you mention are partly dealt with on the SSO branch and will be solved for good with the release.

**Comment by ghjansen** [comment]
By the last commit for this issue we have the following access scenario:

**Accounts API**: an account can manage its own info and also info from its immediate sub accounts only.
**Applications API**: an account can manage its own applications only.
**IncomingPhoneNumbers API**: an account can manage its numbers and the numbers from its immediate sub accounts only.

Having in mind that we need to focus on Roles in soon, as mentioned on issues #272 and #440, maybe the implementation of this issue could be reviewed to make sure it will not conflict with, or cause unexpected behaviours after Roles became fully functional. I can do this ;)

**Comment by ghjansen** [comment]
@deruelle now with 8a55ef65c8ac21d7a61caafb4c321f4149f3f24b the applications shown at AdminUI (both Local/RAS lists and combo box fields selectors) are filtered to the logged user, avoiding view of applications from different owners.

To do so, I added the email field on Accounts API. I'm not so confident with that because Twilio doesn't have the email field on Accounts API. Anyway, RVD projects owners are currently stored using email only, so i see this as the simplest way to get it done, otherwise we may need to change RVD projects structure.

**Comment by otsakir** [comment]
@ghjansen , I've added email too on the SSO branch. It seems that there more reasons to keep it there.

**Comment by ghjansen** [comment]
Thanks for your confirmation @otsakir , its good to know. With the new access control between accounts, maybe it wont be a sensitive information after all.
