### ISSUE TITLE
Building restcomm fails due to change in name of the SIP Servlets Job

### ISSUE THREAD

**Issue by uppaljs** [Mobicents/RestComm#94]
Hi,

I am trying to follow the documentation at http://docs.telestax.com/restcomm-mobicents-building-from-source/ , The build script when executed fails giving a 404 as build.xml is point to https://mobicents.ci.cloudbees.com/job/Mobicents-SipServlets-Release whereas the actual release name on cloudbees has been changed to https://mobicents.ci.cloudbees.com/job/Mobicents-SipServlets-Release_ANTI_DDOS.

A quick search and replace for Mobicents-SipServlets-Release with Mobicents-SipServlets-Release_ANTI_DDOS in release/build.xml atleast fixes the 404 issue , the documentation and the build file needs to be updated.

**Comment by scottbarstow** [comment]
@deruelle What's the new urls?  I'm trying to build from scratch and neither of the urls above work.  I just did a brand new clone to confirm.

**Comment by scottbarstow** [comment]
I fixed this in my build file by changing the sipservlets-build property to 578 from 564 (checked in version).

**Comment by scottbarstow** [comment]
Yes, will do.

On Wed, Mar 18, 2015 at 4:46 AM, Jean Deruelle <notifications@github.com>
wrote:

> Great, please send a PR for that too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mobicents/RestComm/issues/94#issuecomment-82823390>.
>



-- 
scottbarstow.com
@scottbarstow
